README.md
Add Codecov markdown badge for easy visualisation of Codecov percentage
=> Add Codecov markdown badge to README.md

docs/AboutUs.md, docs/team/zenkoh1.md
=> Update AboutUs for Zen

docs/AboutUs.md, docs/team/brendanng7.md
=> Update AboutUs for Brendan

docs/AboutUs.md, docs/team/linette.md
=> Update AboutUs for Linette

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/MarkCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/contactdate/ContactDate.java, src/main/java/seedu/address/model/contactdate/ContactDateList.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedContactDate.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/MarkCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java, src/test/java/seedu/address/model/contactdate/ContactDateListTest.java, src/test/java/seedu/address/model/contactdate/ContactDateTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- Implement custom `ArrayList` to keep track of contact dates (`ContactDateList`) 
- Implement ability to mark person as contacted. This creates a `ContactDate` for today's date and adds it to the `ContactDateList`
- Add new array in JSON to store the contact dates
- Implement tests for relevent features
Closes: https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/37
=> Implement mark elderly as contacted

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/person/Nric.java, src/main/java/seedu/address/model/person/Person.java
=> Improve code style for nric implementation

src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/41
=> Implement handling of empty list when parsing JSON

src/test/java/seedu/address/model/person/NricTest.java
=> Improve Nric test cases

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/person/PersonTest.java
This PR adds a warning if you have similar persons in the existing address book (ie. you have the same name, same phone number or same email) for:
1. Adding a new (similar) person
2. Editing a person to become similar to another person
Closes #58
=> Soft check duplicates

src/main/java/seedu/address/logic/Messages.java
The tags and call frequency are not formatted correctly
=> Fix person format method

build.gradle, docs/UserGuide.md, src/main/java/seedu/address/ui/HelpWindow.java, src/main/resources/view/HelpWindow.fxml
Changed the user guide shown to be ContactMate's instead of AB-3's. 
Added a way to view the UserGuide website from the app.
Closes #61
=> Improve Help Window 

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/ui/CallHistoryPanel.java, src/main/java/seedu/address/ui/MainWindow.java
Refactor duplicate panel switching logic into a single method
Update the personList after mark command
closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/66
closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/68
=> Refactoring panel switching and update PersonList after mark command

build.gradle, docs/UserGuide.md, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/ui/HelpWindow.java, src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json, src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
=> Remove AB3 references from UG

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/contactrecord/ContactRecord.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/storage/JsonAdaptedContactRecord.java, src/main/java/seedu/address/ui/CallHistoryCard.java, src/main/java/seedu/address/ui/CallHistoryPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/CallHistoryCard.fxml, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/HistoryCommandTest.java, src/test/java/seedu/address/model/contactrecord/ContactRecordTest.java, src/test/java/seedu/address/testutil/ContactRecordBuilder.java
- adds notes to history card
- fixes padding for history card
- notes are text wrapped
- refactor add method to return Local Date
- update toString() of ContactRecord
Closes #55 
Closes #62 
Closes #71 
Closes #72
=> Update history card to include notes

src/main/resources/view/PersonListCard.fxml
Closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/56
=> Add labels to Person details

src/main/java/seedu/address/ui/HelpWindow.java
Seems like an invalid date was added. 
Closes #93
=> Fix help window

docs/AboutUs.md
=> Remove portfolio link on AboutUs

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java
closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/113
closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/111
=> Change the phrasing of call frequency and update the tags

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/model/Model.java
=> Update use cases

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/HistoryListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ProfileView.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/HistoryListPanel.fxml, src/main/resources/view/ProfileView.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java
This is the basic view, and the UI has not been updated yet. It depends on the changes to the overall UI. (like changing the colour?...) 
It will fail Codecov :')
closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/183
=> Add profile view in HistoryListPanel

docs/UserGuide.md
=> Add Glossary to UG

docs/DeveloperGuide.md, docs/UserGuide.md
Closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/261
Closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/259
Closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/242
Closes https://github.com/AY2425S1-CS2103T-F14b-3/tp/issues/205
=> Update UG and DG with regards to PE Dry Run

docs/DeveloperGuide.md
Will wait for the other enhancement PRs to be merged before merging this
Closes #224
=> Add NRIC field enhancement
